// This file was generated by ChatGPT by asking it to port logfire/_internal/scrubbing.py to TypeScript.

export type JsonPath = (number | string)[]
export interface ScrubbedNote {
  matched_substring: string
  path: JsonPath
}

export interface ScrubMatch {
  path: JsonPath
  patternMatch: RegExpMatchArray
  value: unknown
}

export type ScrubCallback = (match: ScrubMatch) => unknown

/**
 * Interface for attribute scrubbers that can process values and potentially
 * redact sensitive information.
 */
export interface AttributeScrubber {
  /**
   * Scrubs a value recursively.
   * @param path The JSON path to this value.
   * @param value The value to scrub.
   * @returns A tuple: [scrubbedValue, scrubbedNotes]
   */
  scrubValue(path: JsonPath, value: unknown): readonly [unknown, ScrubbedNote[]]
}

/**
 * Base interface for attribute scrubbers with safe keys
 */
export interface BaseScrubber extends AttributeScrubber {
  /**
   * List of keys that are considered safe and do not need scrubbing
   */
  SAFE_KEYS: string[]

  /**
   * Scrubs a value recursively.
   * @param path The JSON path to this value.
   * @param value The value to scrub.
   * @returns A tuple: [scrubbedValue, scrubbedNotes]
   */
  scrubValue<T>(path: JsonPath, value: T): readonly [T, ScrubbedNote[]]
}

const DEFAULT_PATTERNS = [
  'password',
  'passwd',
  'mysql_pwd',
  'secret',
  'auth(?!ors?\\b)',
  'credential',
  'private[._ -]?key',
  'api[._ -]?key',
  'session',
  'cookie',
  'csrf',
  'xsrf',
  'jwt',
  'ssn',
  'social[._ -]?security',
  'credit[._ -]?card',
]

// Should be kept roughly in sync with `logfire._internal.scrubbing.BaseScrubber.SAFE_KEYS`
const SAFE_KEYS = new Set([
  // The Agent Control config hint, reported by `logfire/agent-control` and by every adapter built on
  // it. `agent_control.baseline` is the agent's own source text -- the prompt and tool descriptions
  // its author wrote, with request-derived values already kept out by the contract that builds it --
  // and it is the document a config is created from, digested by `agent_control.baseline_sha256` and
  // sized by `agent_control.baseline_bytes`. Redacting a word inside it corrupts that document and
  // silently breaks both. The identity and deployment attributes go with it: the same service name,
  // environment and version already arrive unscrubbed as OTel resource attributes, which are not
  // scrubbed, so redacting the copy on this span protects nothing and costs the consumer the agent it
  // names.
  'agent_control.agent_name',
  'agent_control.baseline',
  'agent_control.environment',
  'agent_control.service_name',
  'agent_control.service_version',
  'agent_control.variable_name',
  'code.filepath',
  'code.function',
  'code.lineno',
  'db.plan',
  'db.statement',
  'exception.stacktrace',
  'exception.type',
  'http.method',
  'http.route',
  'http.scheme',
  'http.status_code',
  'http.target',
  'http.url',
  'logfire.json_schema',
  'logfire.level_name',
  'logfire.level_num',
  'logfire.logger_name',
  'logfire.msg',
  'logfire.msg_template',
  'logfire.null_args',
  'logfire.package_versions',
  'logfire.pending_parent_id',
  'logfire.sample_rate',
  'logfire.scrubbed',
  'logfire.span_type',
  'logfire.tags',
  'schema.url',
  'url.full',
  'url.path',
  'url.query',
])

// Attribute keys under these prefixes are safe, for the same reason as `SAFE_KEYS` but where the key
// is built at runtime and cannot be listed. This is the SDK exempting its own instrumentation's
// namespace, not a general opt-out: nothing outside this module adds to it. Kept in sync with
// `logfire._internal.scrubbing.BaseScrubber.SAFE_KEY_PREFIXES`.
//
// `logfire.variables.<name>` carries which label of a managed variable served the run, and `.version`
// the version number, on every span inside the resolution. The name is the developer's variable name,
// so a variable called `agent__auth_router` or `prompt__session_summary` matched on its *key* and had
// its label redacted -- losing the version attribution that makes a managed variable auditable, on
// every span of the run, while protecting nothing: what the value holds is a label the same developer
// chose.
const SAFE_KEY_PREFIXES = ['logfire.variables.']

/** Whether an attribute key and everything under it is kept whatever the patterns match. */
function isSafeKey(key: string): boolean {
  return SAFE_KEYS.has(key) || SAFE_KEY_PREFIXES.some((prefix) => key.startsWith(prefix))
}

const MAX_SCRUB_DEPTH = 100
const MAX_DEPTH_REPLACEMENT = '[Scrubbed due to max depth]'
const CYCLE_REPLACEMENT = '[Scrubbed due to cycle]'

export class LogfireAttributeScrubber implements BaseScrubber {
  /**
   * List of keys that are considered safe and don't need scrubbing
   */
  SAFE_KEYS: string[] = Array.from(SAFE_KEYS)
  private readonly callback?: ScrubCallback

  private readonly pattern: RegExp

  constructor(patterns?: string[], callback?: ScrubCallback) {
    const allPatterns = [...DEFAULT_PATTERNS, ...(patterns ?? [])]
    this.pattern = new RegExp(allPatterns.join('|'), 'iu')
    if (callback !== undefined) {
      this.callback = callback
    }
  }

  /**
   * Scrubs a value recursively using default patterns.
   * @param path The JSON path to this value.
   * @param value The value to scrub.
   * @returns A tuple: [scrubbedValue, scrubbedNotes]
   */
  scrubValue<T>(path: JsonPath, value: T): readonly [T, ScrubbedNote[]] {
    const scrubbedNotes: ScrubbedNote[] = []
    const scrubbedValue = this.scrub(path, value, scrubbedNotes, new WeakSet(), 0)
    return [scrubbedValue as T, scrubbedNotes] as const
  }

  private redact(path: JsonPath, value: unknown, match: RegExpMatchArray, notes: ScrubbedNote[]): unknown {
    // If callback is provided and returns a non-null value, use that
    if (this.callback) {
      const callbackResult = this.callback({ path, patternMatch: match, value })
      if (callbackResult !== null && callbackResult !== undefined) {
        return callbackResult
      }
    }

    const matchedSubstring = match[0]
    notes.push({ matched_substring: matchedSubstring, path })
    return `[Scrubbed due to '${matchedSubstring}']`
  }

  private scrub(path: JsonPath, value: unknown, notes: ScrubbedNote[], seen: WeakSet<object>, depth: number): unknown {
    if (typeof value === 'string') {
      // Check if the string matches the pattern
      const match = value.match(this.pattern)
      if (match) {
        // If the entire string is just the matched pattern, consider it safe.
        // e.g., if value == 'password', just leave it.
        if (!(match.index === 0 && match[0].length === value.length)) {
          // Try to parse as JSON
          try {
            const parsed = JSON.parse(value) as unknown
            if (depth >= MAX_SCRUB_DEPTH) {
              return this.redact(path, value, match, notes)
            }
            // If parsed, scrub the parsed object
            const newVal = this.scrub(path, parsed, notes, seen, depth + 1)
            return JSON.stringify(newVal)
          } catch {
            // Not JSON, redact directly
            return this.redact(path, value, match, notes)
          }
        }
      }
      return value
    } else if (value instanceof Date) {
      return value
    } else if (Array.isArray(value)) {
      if (depth >= MAX_SCRUB_DEPTH) {
        return MAX_DEPTH_REPLACEMENT
      }
      if (seen.has(value)) {
        return CYCLE_REPLACEMENT
      }
      seen.add(value)
      try {
        return value.map((v, i) => this.scrub([...path, i], v, notes, seen, depth + 1))
      } finally {
        seen.delete(value)
      }
    } else if (value !== null && typeof value === 'object') {
      if (depth >= MAX_SCRUB_DEPTH) {
        return MAX_DEPTH_REPLACEMENT
      }
      if (seen.has(value)) {
        return CYCLE_REPLACEMENT
      }
      seen.add(value)
      // Object. Rebuilt through a Map: keys are user data, and assigning to a `__proto__` key
      // would replace the rebuilt record's prototype instead of keeping the entry.
      try {
        const result = new Map<string, unknown>()
        for (const [k, v] of Object.entries(value)) {
          if (isSafeKey(k) || ['boolean', 'number', 'undefined'].includes(typeof v) || v === null) {
            // Safe key or a primitive value, no scrubbing of the key itself.
            // (In the Python SDK we still scrub primitive values to be extra careful)
            result.set(k, v)
          } else {
            // Check key against the pattern
            const keyMatch = k.match(this.pattern)
            if (keyMatch) {
              // Key contains sensitive substring
              const redacted = this.redact([...path, k], v, keyMatch, notes)
              // If v is an object/array and got redacted to a string, we may want to consider if that's correct.
              // For simplicity, we just store the redacted string.
              result.set(k, redacted)
            } else {
              // Scrub the value recursively
              result.set(k, this.scrub([...path, k], v, notes, seen, depth + 1))
            }
          }
        }
        return Object.fromEntries(result)
      } finally {
        seen.delete(value)
      }
    }

    return value
  }
}

/**
 * A no-op attribute scrubber that returns values unchanged.
 * Useful when you want to disable scrubbing entirely.
 */
export class NoopAttributeScrubber implements BaseScrubber {
  /**
   * List of keys that are considered safe and don't need scrubbing
   */
  SAFE_KEYS: string[] = []

  /**
   * Returns the value unchanged with no scrubbing notes.
   * @param path The JSON path to this value.
   * @param value The value to return unchanged.
   * @returns A tuple: [originalValue, emptyNotes]
   */
  scrubValue<T>(_path: JsonPath, value: T): readonly [T, ScrubbedNote[]] {
    return [value, []] as const
  }
}

/**
 * A singleton instance of NoopAttributeScrubber for convenience
 */
export const NoopScrubber: NoopAttributeScrubber = new NoopAttributeScrubber()
