packages:
  - 'packages/*'
  - 'examples/*'
  - '!examples/nextjs-bun'

strictPeerDependencies: true
autoInstallPeers: false
resolvePeersFromWorkspaceRoot: false

overrides:
  '@opentelemetry/core@<2.8.0': '2.8.0'
  '@opentelemetry/resources@<2.8.0': '2.8.0'
  '@opentelemetry/sdk-trace-base@<2.8.0': '2.8.0'
  '@opentelemetry/sdk-trace-web@<2.8.0': '2.8.0'
  '@opentelemetry/semantic-conventions@<1.41.1': '1.41.1'
  '@grpc/proto-loader@0.8.0>protobufjs': '7.6.3'
  '@grpc/grpc-js@^1.14.3': '1.14.4'
  '@manypkg/get-packages@1.1.3>read-yaml-file': '2.1.0'
  '@changesets/parse>js-yaml': '4.2.0'
  '@opentelemetry/otlp-transformer@0.217.0>protobufjs': '8.6.4'
  'path-to-regexp@<0.1.13': '0.1.13'
  'picomatch@<2.3.2': '2.3.2'
  'postcss@<8.5.10': '8.5.12'
  'qs@>=6.7.0 <=6.15.1': '6.15.2'
  'wrangler>esbuild': '0.28.1'
  'undici@>=7.0.0 <7.24.0': '>=7.24.0'
  'vite': 'npm:@voidzero-dev/vite-plus-core@0.2.1'
  'vitest': '4.1.9'

catalog:
  '@opentelemetry/api': ^1.9.1
  '@opentelemetry/api-logs': '>=0.217.0 <0.300.0'
  '@opentelemetry/auto-instrumentations-node': '>=0.77.0 <0.100.0'
  '@opentelemetry/auto-instrumentations-web': '>=0.64.0 <0.100.0'
  '@opentelemetry/context-async-hooks': ^2.8.0
  '@opentelemetry/context-zone': ^2.8.0
  '@opentelemetry/core': ^2.8.0
  '@opentelemetry/exporter-logs-otlp-proto': '>=0.219.0 <0.300.0'
  '@opentelemetry/exporter-metrics-otlp-proto': '>=0.219.0 <0.300.0'
  '@opentelemetry/exporter-trace-otlp-http': '>=0.219.0 <0.300.0'
  '@opentelemetry/exporter-trace-otlp-proto': '>=0.219.0 <0.300.0'
  '@opentelemetry/instrumentation': '>=0.219.0 <0.300.0'
  '@opentelemetry/instrumentation-fetch': '>=0.219.0 <0.300.0'
  '@opentelemetry/instrumentation-user-interaction': '>=0.63.0 <0.100.0'
  '@opentelemetry/otlp-exporter-base': '>=0.219.0 <0.300.0'
  '@opentelemetry/otlp-transformer': '>=0.219.0 <0.300.0'
  '@opentelemetry/resources': ^2.8.0
  '@opentelemetry/sdk-logs': '>=0.219.0 <0.300.0'
  '@opentelemetry/sdk-metrics': ^2.8.0
  '@opentelemetry/sdk-node': '>=0.219.0 <0.300.0'
  '@opentelemetry/sdk-trace-base': ^2.8.0
  '@opentelemetry/sdk-trace-node': ^2.8.0
  '@opentelemetry/sdk-trace-web': ^2.8.0
  '@opentelemetry/semantic-conventions': ^1.41.1
  '@types/js-yaml': ^4.0.9
  '@vercel/otel': ^2.1.2
  handlebars: ^4.7.9
  'js-yaml': ^4.2.0
  'p-retry': ^6.2.1
  typescript: ^6.0.3
  vitest: 4.1.9
  zod: ^3.23.8

allowBuilds:
  esbuild: true
  protobufjs: true
  sharp: false
  workerd: true

minimumReleaseAgeExclude:
  - '@voidzero-dev/vite-plus-core@0.2.1'
  - '@voidzero-dev/vite-plus-darwin-arm64@0.2.1'
  - '@voidzero-dev/vite-plus-darwin-x64@0.2.1'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.2.1'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@0.2.1'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@0.2.1'
  - '@voidzero-dev/vite-plus-linux-x64-musl@0.2.1'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.2.1'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@0.2.1'
  - vite-plus@0.2.1
